---
abstract: 'File globbing utility'
author:
  - 'Yanick Champoux <yanick@cpan.org>'
build_requires:
  Cwd: '0'
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Test2::V0: '0'
  Test::More: '0'
  perl: '5.006'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.012, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Path-Tiny-Glob
provides:
  Path::Tiny::Glob:
    file: lib/Path/Tiny/Glob.pm
    version: v0.2.0
  Path::Tiny::Glob::Visitor:
    file: lib/Path/Tiny/Glob/Visitor.pm
    version: v0.2.0
requires:
  Exporter::Tiny: '0'
  List::Lazy: '0'
  Moo: '0'
  Path::Tiny: '0'
  experimental: '0'
  parent: '0'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/yanick/Path-Tiny-Glob/issues
  homepage: https://github.com/yanick/Path-Tiny-Glob
  repository: https://github.com/yanick/Path-Tiny-Glob.git
version: 0.2.0
x_author_pledge:
  version: 1
x_authority: cpan:YANICK
x_contributor_covenant:
  version: 0.02
x_generated_by_perl: v5.30.0
x_serialization_backend: 'YAML::Tiny version 1.73'
